# Generated by Django 4.2 on 2023-04-23 17:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sale_leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatorapartment',
            name='contact_id',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=200, null=True, verbose_name='Contact Id'),
        ),
        migrations.AlterField(
            model_name='flatorapartment',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=200, null=True, verbose_name='Location'),
        ),
    ]
