# Generated by Django 4.2 on 2023-04-23 18:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sale_leads', '0002_alter_flatorapartment_contact_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatorapartment',
            name='certifications',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('occupation_certificate', 'Occupation Certificate'), ('commencement_certificate', 'Commencement Certificate')], max_length=60, null=True, verbose_name='Available Certifications'),
        ),
    ]
