# Generated by Django 4.1.7 on 2023-05-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_leads', '0009_saleleadsbungalow'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatorapartment',
            name='possession',
            field=models.CharField(blank=True, choices=[('ready_to_move', 'Ready To Move'), ('under_construction', 'Under Construction')], max_length=50, null=True, verbose_name='Possession'),
        ),
        migrations.AddField(
            model_name='flatorapartment',
            name='possession_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age of Property'),
        ),
        migrations.AddField(
            model_name='flatorapartment',
            name='possession_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
