# Generated by Django 4.1.7 on 2023-05-16 16:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sale_leads', '0011_saleleadsbungalow_possession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleleadsbungalow',
            name='interiors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Empty', 'Empty / Unfurnished'), ('Semi', 'Semi Furnished'), ('Fully', 'Fully Furnished')], max_length=30, null=True, verbose_name='Interiors'),
        ),
        migrations.AlterField(
            model_name='saleleadsbungalow',
            name='kitchen',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Empty', 'Empty'), ('Shelves', 'Shelves'), ('Modular', 'Modular')], max_length=30, null=True, verbose_name='Kitchen'),
        ),
        migrations.AlterField(
            model_name='saleleadsbungalow',
            name='vastu_exit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South')], max_length=30, null=True, verbose_name='Vastu / Exit'),
        ),
    ]
