# Generated by Django 4.1.8 on 2023-04-30 12:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sale_inventory', '0004_flatorapartment_property_utility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatorapartment',
            name='contact_id',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'mr Raj Kumar '), (2, 'Shiva '), (3, 'Rajesh '), (5, 'Mahesh '), (6, 'Salman Bhai '), (10, 'hello '), (4, 'Mallesh '), (11, 'Mars '), (12, 'elon '), (13, 'Jeff '), (7, 'I am ')], max_length=25, null=True, verbose_name='Contact Id'),
        ),
        migrations.AlterField(
            model_name='flatorapartment',
            name='property_utility',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Agricultural', 'Agricultural'), ('Commercial', 'Commercial'), ('Educational', 'Educational'), ('Hospital', 'Hospital'), ('Industrial', 'Industrial'), ('Lodging / Hotel', 'Lodging / Hotel'), ('Recreational', 'Recreational'), ('Residential', 'Residential'), ('Restaurant / Dinner', 'Restaurant / Dinner')], max_length=116, null=True, verbose_name='Property Utility'),
        ),
    ]
