# Generated by Django 4.1.8 on 2023-05-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_inventory', '0007_saleinventorybungalow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatorapartment',
            name='flat_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Flat No.'),
        ),
    ]
