# Generated by Django 4.1.7 on 2023-05-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_inventory', '0008_alter_flatorapartment_flat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatorapartment',
            name='interiors',
            field=models.CharField(blank=True, choices=[('Empty', 'Empty / Unfurnished'), ('Semi', 'Semi Furnished'), ('Fully', 'Fully Furnished')], max_length=30, null=True, verbose_name='Interiors'),
        ),
        migrations.AlterField(
            model_name='flatorapartment',
            name='kitchen',
            field=models.CharField(blank=True, choices=[('Empty', 'Empty'), ('Shelves', 'Shelves'), ('Modular', 'Modular')], max_length=30, null=True, verbose_name='Kitchen'),
        ),
        migrations.AlterField(
            model_name='flatorapartment',
            name='vastu_exit',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South')], max_length=30, null=True, verbose_name='Vastu / Exit'),
        ),
    ]
