# Generated by Django 4.1.7 on 2023-06-03 15:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sale_inventory', '0011_saleinventorycommercialoffice_saleinventoryshop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInventoryCottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'mr Raj Kumar '), (2, 'Shiva '), (3, 'Rajesh '), (5, 'Mahesh '), (6, 'Salman Bhai '), (10, 'hello '), (4, 'Mallesh '), (11, 'Mars '), (12, 'elon '), (13, 'Jeff '), (7, 'I am ')], max_length=25, null=True, verbose_name='Contact Id')),
                ('property_utility', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Agricultural', 'Agricultural'), ('Commercial', 'Commercial'), ('Educational', 'Educational'), ('Hospital', 'Hospital'), ('Industrial', 'Industrial'), ('Lodging / Hotel', 'Lodging / Hotel'), ('Recreational', 'Recreational'), ('Residential', 'Residential'), ('Restaurant / Dinner', 'Restaurant / Dinner')], max_length=116, null=True, verbose_name='Property Utility')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Tags')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('inventory_id', models.BigIntegerField(unique=True, verbose_name='Inventory Id')),
                ('created_by', models.IntegerField(null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(null=True, verbose_name='Updated By')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Video Link')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('partitions', models.IntegerField(blank=True, null=True, verbose_name='Partitions')),
                ('bathroom', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Bathroom')),
                ('carpet_units', models.CharField(blank=True, choices=[('sq ft', 'sq ft'), ('sq mt', 'sq mt')], max_length=5, null=True, verbose_name='Carpet Units')),
                ('carpet_area', models.IntegerField(blank=True, null=True, verbose_name='Carpet Area')),
                ('builtup_units', models.CharField(blank=True, choices=[('sq ft', 'sq ft'), ('sq mt', 'sq mt')], max_length=5, null=True, verbose_name='Built-up Units')),
                ('builtup_area', models.IntegerField(blank=True, null=True, verbose_name='Built-up Area')),
                ('total_floor', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25')], null=True, verbose_name='Total Floor')),
                ('vastu_exit', models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South')], max_length=30, null=True, verbose_name='Vastu / Exit')),
                ('interiors', models.CharField(blank=True, choices=[('Empty', 'Empty / Unfurnished'), ('Semi', 'Semi Furnished'), ('Fully', 'Fully Furnished')], max_length=30, null=True, verbose_name='Interiors')),
                ('kitchen', models.CharField(blank=True, choices=[('Empty', 'Empty'), ('Shelves', 'Shelves'), ('Modular', 'Modular')], max_length=30, null=True, verbose_name='Kitchen')),
                ('room_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Office No.')),
                ('cts_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Wing')),
                ('society_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Building Name')),
                ('street_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Name')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('landmark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark')),
                ('google_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Google Location')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('sale_price', models.BigIntegerField(blank=True, null=True, verbose_name='Sale Price')),
                ('ownership', models.CharField(blank=True, choices=[('new', 'New'), ('resale', 'Resale')], max_length=10, null=True, verbose_name='Ownership')),
                ('possession', models.CharField(blank=True, choices=[('ready_to_move', 'Ready To Move'), ('under_construction', 'Under Construction')], max_length=50, null=True, verbose_name='Possession')),
                ('possession_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age of Property')),
                ('possession_due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('parking', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True, verbose_name='Parking')),
                ('certifications', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('occupation_certificate', 'Occupation Certificate'), ('commencement_certificate', 'Commencement Certificate')], max_length=50, null=True, verbose_name='Available Certifications')),
                ('amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('VISITOR_PARKING', 'Visitor Parking'), ('WATER_HARVESTING', 'Water Harvesting'), ('SEWAGE_TREATMENT', 'Sewage Treatment'), ('INTERCOM', 'Intercom'), ('GARBAGE_DISPOSAL', 'Garbage Disposal'), ('SECURITY', 'Security')], max_length=84, null=True, verbose_name='Amenities')),
                ('other_features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ROAD_TOUCH', 'Road Touch'), ('JODI', 'Jodi'), ('MEZANINE', 'Mezanine'), ('ROAD_FACING', 'Road Facing'), ('WATER_CONNECTION', 'Water Connection'), ('SINGLE_PHASE_CONNECTION', 'Single Phase Connection'), ('THREE_PHASE_CONNECTION', 'Three Phase Connection'), ('FIRE_EXIT', 'Fire Exit'), ('PILLARLESS', 'Pillarless'), ('GAS_PIPELINE', 'Gas Pipeline')], max_length=134, null=True, verbose_name='Other Features')),
                ('property_status', models.CharField(blank=True, choices=[('to_confirm', 'To Confirm'), ('active', 'Active'), ('sold', 'Sold')], default='to_confirm', max_length=10, null=True, verbose_name='Property Status')),
                ('delete_flag', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cottage',
                'db_table': 'sale_inventory_cottage',
            },
        ),
    ]
