# Generated by Django 4.1.7 on 2023-06-06 12:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sale_inventory', '0012_saleinventorycottage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinventoryshop',
            name='office_no',
        ),
        migrations.AddField(
            model_name='saleinventoryshop',
            name='shop_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Shop No.'),
        ),
        migrations.AlterField(
            model_name='saleinventorycommercialoffice',
            name='other_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MEZANINE', 'Mezanine'), ('ROAD_FACING', 'Road Facing'), ('SINGLE_PHASE_CONNECTION', 'Single Phase Connection'), ('THREE_PHASE_CONNECTION', 'Three Phase Connection'), ('FIRE_EXIT', 'Fire Exit'), ('PILLARLESS', 'Pillarless'), ('JODI', 'Jodi')], max_length=93, null=True, verbose_name='Other Features'),
        ),
        migrations.AlterField(
            model_name='saleinventorycottage',
            name='cts_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CTS No'),
        ),
        migrations.AlterField(
            model_name='saleinventorycottage',
            name='other_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ROAD_TOUCH', 'Road Touch'), ('JODI', 'Jodi'), ('MEZANINE', 'Mezanine'), ('BASEMENT', 'Basement'), ('ROAD_FACING', 'Road Facing'), ('WATER_CONNECTION', 'Water Connection'), ('SINGLE_PHASE_CONNECTION', 'Single Phase Connection'), ('THREE_PHASE_CONNECTION', 'Three Phase Connection'), ('FIRE_EXIT', 'Fire Exit'), ('PILLARLESS', 'Pillarless'), ('GAS_PIPELINE', 'Gas Pipeline')], max_length=143, null=True, verbose_name='Other Features'),
        ),
        migrations.AlterField(
            model_name='saleinventorycottage',
            name='room_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Room No.'),
        ),
        migrations.AlterField(
            model_name='saleinventorycottage',
            name='society_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Society Name'),
        ),
        migrations.AlterField(
            model_name='saleinventorycottage',
            name='total_floor',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25')], null=True, verbose_name='Total Floors'),
        ),
        migrations.AlterField(
            model_name='saleinventoryshop',
            name='other_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ROAD_TOUCH', 'Road Touch'), ('JODI', 'Jodi'), ('MEZANINE', 'Mezanine'), ('BASEMENT', 'Basement'), ('ROAD_FACING', 'Road Facing'), ('WATER_CONNECTION', 'Water Connection'), ('SINGLE_PHASE_CONNECTION', 'Single Phase Connection'), ('THREE_PHASE_CONNECTION', 'Three Phase Connection'), ('FIRE_EXIT', 'Fire Exit'), ('PILLARLESS', 'Pillarless'), ('GAS_PIPELINE', 'Gas Pipeline')], max_length=143, null=True, verbose_name='Other Features'),
        ),
    ]
