# Generated by Django 4.1.8 on 2023-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_alter_contacts_email_alter_contacts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contact_label',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('brokers_estate_agents', 'Brokers/Estate Agents'), ('developers', 'Developers'), ('maintenance', 'Maintenance'), ('it_support', 'IT Support'), ('legal', 'Legal'), ('others', 'Others')], max_length=30, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='custom_link',
            field=models.URLField(blank=True, null=True, verbose_name='Custom Link'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Link'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok Link'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter Link'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Link'),
        ),
    ]
